### ISSUE TITLE
Test all features across different devices and browsers.

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#17]

**Comment by UBC-Yang** [comment]
User Story:
As a user
I want the application to be adjusted across different browsers and devices

Acceptance Criteria:
WHEN I open the application on the default browser
THEN I am presented with an organized page 
WHEN I switch to a different device
THEN the formation of the page will be adjusted accordingly to present a nice review
WHEN I click on the different functions of the application
THEN I am presented with a responsive and user-friendly page
