### ISSUE TITLE
Create a modal library for interactions that require user input.

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#2]

**Comment by UBC-Yang** [comment]
User Sory:
As a user
I want to be able to input grocery expiration dates manually

Acceptance Criteria:
WHEN I click on the "+" button, 
THEN a modal form will appear asking for the item name, quantity, and expiration date
WHEN I click on the "Add Item" button in the form
THEN user input will be saved to local storage
WHEN I view the grocery list
THEN I see all the items I have added
WHEN I click on the "Delete" button next to the item
THEN item is removed from the grocery list
WHEN I refresh the page
THEN the saved tasks persist
